### ISSUE TITLE
Videos not playing on iOS9 GM

### ISSUE THREAD

**Issue by rjgdesign** [piemonte/Player#34] opened 2015-09-13 13:45 UTC
Hey,

Videos don't seem to play on iOS9 GM, the player.view remains hidden. Any ideas?

Cheers!

**Comment by rjgdesign** [comment] 2015-09-13 14:38
Using the Swift 2.0 branch - and it seems to be local files being the issue, using the file path:

/private/var/mobile/Containers/Data/Application/8B93DD67-7346-4CEC-9A24-EDEB1F59C1BD/tmp/video_D67A462C-E7FC-4EAD-9E5F-1DF1C37EA8E8.mp4

**Comment by austinllach** [comment] 2015-09-22 16:14
Same problem... I'm trying to figure it out right now

**Comment by austinllach** [comment] 2015-09-22 17:00
The problem is in Player.swift the url is never being set as local and only remote.

Here is one way to play local files...

Set the path for the player (mov or mp4)
self.player.path = NSBundle.mainBundle().pathForResource("video", ofType: "mov")!


Then in Player.swift check if the remoteURL scheme is an empty string. Remote url's will have "http" or "https" and local urls will have " "

example code below...

 if remoteUrl != nil && remoteUrl?.scheme != nil && remoteUrl!.scheme != "" {
                let asset = AVURLAsset(URL: remoteUrl!, options: .None)
                self.setupAsset(asset)
                
            } else {
                let localURL: NSURL? = NSURL(fileURLWithPath: newValue)
                let asset = AVURLAsset(URL: localURL!, options: .None)
                self.setupAsset(asset)
                
            }

**Comment by austinllach** [comment] 2015-09-22 17:01
There is probably a better way, but that is a quick solution

**Comment by erautenberg** [comment] 2015-10-07 18:34
I'm having this problem with local videos as well, but it does not seem to be a problem with the current version of Player.swift's filepath section because without adding && remoteUrl!.scheme != "", the else statement is still being reached when I provide a local file.  I added a print statement to the else in order to find out what url it is getting, and while the file path printed out is correct, nothing happens.  I'm also having issues with some remote videos, particularly anything that is NOT https.

**Comment by piemonte** [comment] 2015-11-12 00:57
i believe this was fixed by the latest contribution.

https://github.com/piemonte/Player/releases/tag/0.0.8

**Closed by piemonte** 2015-11-12 00:57 UTC
Labels: bug
