### ISSUE TITLE
PlayerDelegate, playerReady(_ player: Player) never trigger sometimes

### ISSUE THREAD

**Issue by Chepond** [piemonte/Player#196] opened 2018-09-16 10:45 UTC
I used the below code to init the player object by setting the url and add subview to my view
it normally works, but sometimes it doesnt load at all, i checked the url by init it on Data, and it shows bytes, and also when the player doesnt show any video, PlayerDelegate, playerReady(_ player: Player) never call. I have been tracing for days still getting no idea how to solves this.
Also when I use the url extracted from PHAsset, the player can only play short duration videos, when it comes to a long one, it has the same issue, I have waited quite a while still no response, and PlayerDelegate, playerReady(_ player: Player) also never call, please help, many thanks

self.player = Player()
if let player = self.player {
               player.playerDelegate = self
                player.playbackDelegate = self
                player.url = url
                player.view.frame = self.vPlayer.bounds
                self.addChildViewController(player)
                self.vPlayer.addSubview(player.view)
}

**Comment by piemonte** [comment] 2018-09-17 00:28
hi @Chepond sounds like a duplicate of this issue

📎 https://github.com/piemonte/Player/issues/195

**Closed by piemonte** 2018-09-17 00:28 UTC

**Comment by Chepond** [comment] 2018-09-17 07:47
> hi @Chepond sounds like a duplicate of this issue
> 
> 📎 #195
I found the problem of playing videos from PHAsset, its caused by the format, .3pg, as all my .mp4 are working well on this thanks. Just the  player(_ player: Player, didFailWithError error: Error?) didnt trigger.. will this be called when unsupported files are set to the player?

but for this problem:
init the player object by setting the url and add subview to my view
it normally works, but sometimes it doesnt load at all, i checked the url by init it on Data, and it shows bytes, and also when the player doesnt show any video, PlayerDelegate, playerReady(_ player: Player) never call. 
the url was actually from NextLevel, NextLevelClip.url, can i just the URL directly or i have to use it through
public init(fileURLWithPath path: String)

many thanks
